org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-25.0.1.8-hotspot

# 핵심 공통 변수 (두 모듈 교차 적용)
mod_version=1.0.0-pre-2+fabric-26.1.2
mod_id=fade
mod_name=Fade
mod_group_id=com.thankun.fade
maven_group=com.thankun.fade
mod_authors=thankun
mod_description=A modern Minecraft utility mod.
mod_license=MIT

# Fabric 빌드 프로퍼티
fabric_minecraft_version=26.1.2
fabric_loader_version=0.19.2
fabric_loom_version=1.16-SNAPSHOT
fabric_api_version=0.150.0+26.1.2